#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

rm -rf "$ROOT/adapters"
"$ROOT/scripts/sync.sh"

test -f "$ROOT/adapters/codex/SKILL.md"
test -f "$ROOT/adapters/codex/agents/openai.yaml"
test -f "$ROOT/adapters/claude/CLAUDE.md"
test -f "$ROOT/adapters/copilot/copilot-instructions.md"
test -f "$ROOT/adapters/gemini/GEMINI.md"
test -f "$ROOT/adapters/opencode/AGENTS.md"
test -f "$ROOT/adapters/cursor/AGENTS.md"

grep -q '^---$' "$ROOT/adapters/codex/SKILL.md"
if grep -q 'Generated by scripts/sync.sh' "$ROOT/adapters/codex/SKILL.md"; then
  echo "codex skill should not contain generated marker comments"
  exit 1
fi
if grep -q 'Generated by scripts/sync.sh' "$ROOT/adapters/codex/agents/openai.yaml"; then
  echo "codex openai.yaml should not contain generated marker comments"
  exit 1
fi
if grep -q 'Generated by scripts/sync.sh' "$ROOT/adapters/claude/CLAUDE.md"; then
  echo "claude adapter should not contain generated marker comments"
  exit 1
fi
if grep -q 'Generated by scripts/sync.sh' "$ROOT/adapters/copilot/copilot-instructions.md"; then
  echo "copilot adapter should not contain generated marker comments"
  exit 1
fi
if grep -q 'Generated by scripts/sync.sh' "$ROOT/adapters/gemini/GEMINI.md"; then
  echo "gemini adapter should not contain generated marker comments"
  exit 1
fi
if grep -q 'Generated by scripts/sync.sh' "$ROOT/adapters/opencode/AGENTS.md"; then
  echo "opencode adapter should not contain generated marker comments"
  exit 1
fi
if grep -q 'Generated by scripts/sync.sh' "$ROOT/adapters/cursor/AGENTS.md"; then
  echo "cursor adapter should not contain generated marker comments"
  exit 1
fi
grep -q '^# ASCII Wireframe for Claude$' "$ROOT/adapters/claude/CLAUDE.md"
grep -q '^# ASCII Wireframe for Copilot$' "$ROOT/adapters/copilot/copilot-instructions.md"
grep -q '^# ASCII Wireframe for Gemini$' "$ROOT/adapters/gemini/GEMINI.md"
grep -q '^# ASCII Wireframe for OpenCode$' "$ROOT/adapters/opencode/AGENTS.md"
grep -q '^# ASCII Wireframe for Cursor$' "$ROOT/adapters/cursor/AGENTS.md"

for adapter in codex claude copilot gemini opencode cursor; do
  test -f "$ROOT/adapters/$adapter/references/example.md"
  test -f "$ROOT/adapters/$adapter/references/legend.md"
  test -f "$ROOT/adapters/$adapter/references/template.md"
done

for file in \
  "$ROOT/adapters/claude/CLAUDE.md" \
  "$ROOT/adapters/copilot/copilot-instructions.md" \
  "$ROOT/adapters/gemini/GEMINI.md" \
  "$ROOT/adapters/opencode/AGENTS.md" \
  "$ROOT/adapters/cursor/AGENTS.md"; do
  if grep -q '^---$' "$file"; then
    echo "non-Codex adapter should not embed YAML frontmatter: $file"
    exit 1
  fi
done
